version: "2"

services:
  voting-app:
<<<<<<< HEAD
    build: ./voting-app/.
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

=======
    image: docker/example-voting-app-voting-app
    ports:
      - "80"
    networks:
      - voteapp
  result-app:
    image: docker/example-voting-app-result-app
    ports:
      - "80"
    networks:
      - voteapp
  worker:
    image: docker/example-voting-app-worker
    networks:
      - voteapp
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - voteapp
    container_name: redis
>>>>>>> c72b8bbda2461f0013e78b6c11a54abea4ccf3b9
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
<<<<<<< HEAD
      - back-tier

=======
      - voteapp
    container_name: db
>>>>>>> c72b8bbda2461f0013e78b6c11a54abea4ccf3b9
volumes:
  db-data:

networks:
<<<<<<< HEAD
  front-tier:
  back-tier:
=======
  voteapp:
>>>>>>> c72b8bbda2461f0013e78b6c11a54abea4ccf3b9
